# Generated by Django 4.1.1 on 2022-12-10 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogpost", name="date",),
        migrations.AddField(
            model_name="blogpost",
            name="published_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
