# Generated by Django 4.1.4 on 2023-01-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="admin", managers=[],),
        migrations.AlterModelManagers(name="teacher", managers=[],),
    ]
