# Generated by Django 4.1.4 on 2023-01-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_admin_managers_alter_teacher_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media/profile_pic'),
        ),
    ]
