# Generated by Django 4.1.1 on 2022-12-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_blogpost_date_blogpost_published_date"),
    ]

    operations = [
        migrations.DeleteModel(name="BlogPost",),
    ]
