# Generated by Django 4.1.4 on 2022-12-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="user",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
    ]
