# Generated by Django 4.1.4 on 2023-01-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="thumbnail",
            field=models.FileField(blank=True, upload_to="thumbnail/%y"),
        ),
    ]
