# Generated by Django 4.1.4 on 2022-12-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="abstract",
            field=models.TextField(default="Write the abstract for your blog"),
        ),
    ]