# Generated by Django 4.1.4 on 2023-01-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="thumbnail",
            field=models.FileField(blank=True, null=True, upload_to="thumbnail/"),
        ),
    ]
