# Generated by Django 4.1.4 on 2022-12-18 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_alter_blogpost_abstract"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="user_favorite",
            field=models.ManyToManyField(
                blank=True, related_name="user_favorite", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
